---
namespace: fabianvf
name: homecluster
version: 0.0.1
readme: README.md
authors:
- Fabian von Feilitzsch <fabian@fabianism.us> www.fabianism.us

description: A collection of Ansible content for deploying and orchestrating a multi-node Kubernetes cluster in a home environment.

license_file: 'LICENSE'
tags: ['kubernetes', 'k8s']

dependencies:
  kubernetes.core: "*"

repository: https://github.com/fabianvf/home-cluster
issues: https://github.com/fabianvf/home-cluster/issues
