---
- name: Create a test PVC
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: test-pvc
        namespace: rook-ceph
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

- name: Wait for test PVC to become bound
  kubernetes.core.k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    name: test-pvc
    namespace: rook-ceph
  register: rook_test_pvc
  until: rook_test_pvc.resources.0.status.phase == "Bound"
  retries: 120
  delay: 30

- name: Delete the test PVC
  kubernetes.core.k8s:
    api_version: v1
    kind: PersistentVolumeClaim
    name: test-pvc
    namespace: rook-ceph
    state: absent
