---
- name: Get murmur pod
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: murmur
    label_selectors:
      - 'app=murmur'
    field_selectors:
      - 'status.phase=Running'
  register: murmur_pods
  until: murmur_pods.resources
  retries: 120
  delay: 30

- name: Generate a SuperUser password
  kubernetes.core.k8s_exec:
    namespace: murmur
    pod: '{{ murmur_pods.resources.0.metadata.name }}'
    command: ./murmur.x86 -ini /opt/murmur/config/murmur.ini -supw {{ lookup('password', password_opts) }}
  vars:
    password_opts: '{{ murmur_password_file }} chars=ascii_letters,digits'
